parameters:
#    gestion_covoiturage.example.class: Gestion\CovoiturageBundle\Example

services:
#    gestion_covoiturage.example:
#        class: %gestion_covoiturage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
