covoiturages:
    pattern:  /
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:index" }

covoiturages_show:
    pattern:  /{id}/show
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:show" }

covoiturages_new:
    pattern:  /new
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:new" }

covoiturages_create:
    pattern:  /create
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:create" }
    requirements: { _method: post }

covoiturages_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:edit" }

covoiturages_update:
    pattern:  /{id}/update
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:update" }
    requirements: { _method: post|put }

covoiturages_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GestionCovoiturageBundle:Covoiturages:delete" }
    requirements: { _method: post|delete }
